version: '3.8'
services:
  wetty_ssh:
    image: wettyoss/wetty:latest
    container_name: wetty_ssh_terminal
    ports:
      - "3031:3000"
    restart: unless-stopped
    environment:
      - WETTY_PORT=3000
      - WETTY_BASE_PATH=/
      - WETTY_COMMAND=ssh
